// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUCjREnJXitheGMXPSsVGWvTsiRor6Tvw',
    appId: '1:945984941623:web:a826167f1af27308a799b2',
    messagingSenderId: '945984941623',
    projectId: 'rafael-gas',
    authDomain: 'rafael-gas.firebaseapp.com',
    databaseURL: 'https://rafael-gas-default-rtdb.firebaseio.com',
    storageBucket: 'rafael-gas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4QWfmsOBrVnCmbHClEJVzNk06LTB5Z7U',
    appId: '1:945984941623:android:78d457efe78eab40a799b2',
    messagingSenderId: '945984941623',
    projectId: 'rafael-gas',
    databaseURL: 'https://rafael-gas-default-rtdb.firebaseio.com',
    storageBucket: 'rafael-gas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg5Ur06NM6OuBpMweLxrKvfZcdy4FoMRE',
    appId: '1:945984941623:ios:908ddb8b538a72d1a799b2',
    messagingSenderId: '945984941623',
    projectId: 'rafael-gas',
    databaseURL: 'https://rafael-gas-default-rtdb.firebaseio.com',
    storageBucket: 'rafael-gas.appspot.com',
    iosBundleId: 'com.example.salesControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg5Ur06NM6OuBpMweLxrKvfZcdy4FoMRE',
    appId: '1:945984941623:ios:908ddb8b538a72d1a799b2',
    messagingSenderId: '945984941623',
    projectId: 'rafael-gas',
    databaseURL: 'https://rafael-gas-default-rtdb.firebaseio.com',
    storageBucket: 'rafael-gas.appspot.com',
    iosBundleId: 'com.example.salesControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUCjREnJXitheGMXPSsVGWvTsiRor6Tvw',
    appId: '1:945984941623:web:a0b0884dde4246c3a799b2',
    messagingSenderId: '945984941623',
    projectId: 'rafael-gas',
    authDomain: 'rafael-gas.firebaseapp.com',
    databaseURL: 'https://rafael-gas-default-rtdb.firebaseio.com',
    storageBucket: 'rafael-gas.appspot.com',
  );

}